trigger:
- main

pr:
- main

jobs:
- job: lint
  displayName: 'Lint Code'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      python -m pip install --upgrade pip
      pip install pylint
    displayName: 'Install dependencies'
  - script: |
      pylint app/*.py
    displayName: 'Run pylint'

- job: test
  displayName: 'Run Tests'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pytest
    displayName: 'Run tests'

- job: deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: 
  - lint
  - test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'your-service-connection-name'
      appName: 'your-web-app-name'
      package: $(Build.ArtifactStagingDirectory)/**/*.zip
      deployToSlotOrASE: true
      ResourceGroupName: 'your-resource-group-name'
      SlotName: 'production'
      publishProfile: $(AZURE_WEBAPP_PUBLISH_PROFILE)