deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Azure Login' # Add this step for Azure login
        uses: azure/login@v2
        with:
          # Configure authentication method here (Service Principal, OIDC, etc.)
          # See https://github.com/azure/login for details and examples.
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Example using Service Principal

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Datasourcing'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
